---
# tasks file for setup-docker
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - python3-pip
      - virtualenv

- name: Add docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu lunar stable
    state: present

- name: Install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
