---
# tasks file for provision_kvm
- name: Install dependencies
  apt:
    name:
      - bridge-utils
      - cpu-checker
      - libvirt-clients
      - libvirt-daemon
      - qemu
      - qemu-kvm
      - libguestfs-tools
      - libvirt-dev
      - openvswitch-switch-dpdk
- name: List VMs
  community.libvirt.virt:
    command: list_vms
  register: vms
  changed_when: no

- name: Create VM if not exists
  block:
    - name: Download base image
      get_url:
      url: "{{ base_image_url }}"
        dest: "/tmp/{{ base_image_name }}"
        checksum: "sha256:4c1543670c8afbfc153320a4e9af3994d58129aa85675ede00b2c3e115ad0838"
    - name: Move to libvirt storage pool
      copy:
        dest: "{{ libvirt_pool_dir }}/{{ vm_name }}.qcow2"
        src: "/tmp/{{ base_image_name }}"
        force: no
        remote_src: yes
        mode: 0660
      register: copy_image
    - name: Configure image
      command: >
        virt-customize -a {{ libvirt_pool_dir }}/{{ vm_name }}.qcow2
        --hostname {{ vm_name }}
        --root-password password:{{ vm_root_pass }}
        --ssh-inject 'root:file:{{ ssh_key }}'
        --uninstall cloud-init
        --touch "/etc/netplan/00-install-config.yaml"
        --write "/etc/netplan/00-install-config.yaml:{{ lookup('template',  '00-install-config.yaml.j2') }}"
        --firstboot-command 'netplan apply'
        --firstboot-command 'netplan generate'
        --firstboot-install openvswitch-switch-dpdk,ssh
        --firstboot-command 'ssh-keygen -A'
        --firstboot-command 'systemctl start ssh'
      when: copy_image is changed
    - name: Define VM
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'ubuntu.xml.j2') }}"
  when: "vm_name not in vms.list_vms"

- name: Start VM
  community.libvirt.virt:
    name: "{{ vm_name }}"
    state: running
  register: vm_started
  until: "vm_started is success"
  retries: 15
  delay: 2
